default: &default
  adapter: postgresql
  encoding: UTF8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: simple_authentication_app_development

test:
  <<: *default
  database: simple_authentication_app_test

production:
  <<: *default
  database: simple_authentication_app_production
  username: simple_authentication_app
  password: <%= ENV["SIMPLE_AUTHENTICATION_APP_DATABASE_PASSWORD"] %>
